blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/carlos-ojeda/carlos-ojeda.github.io/security/policy
    about: Please report security vulnerabilities here.
