name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: portfolio/package-lock.json

    - name: Install dependencies
      run: |
        cd portfolio
        npm ci

    - name: Run tests
      run: |
        cd portfolio
        npm test -- --watchAll=false --passWithNoTests

    - name: Build project
      run: |
        cd portfolio
        npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: portfolio/package-lock.json

    - name: Install dependencies
      run: |
        cd portfolio
        npm ci

    - name: Build project
      run: |
        cd portfolio
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./portfolio/build
        cname: carlos-ojeda.github.io
